stages:
  # - test
  # - check-format
  # - check-types
  - pages

before_script:
  - apt-get update
  - pip install pipenv==2018.11.26
  - make install-deps

# test:
#   stage: test
#   image: python:3.8-slim
#   script:
#     - make run-tests

# check-format:
#   stage: check-format
#   image: python:3.8-slim
#   script:
#     - make check-format

# check-types:
#   stage: check-types
#   image: python:3.8-slim
#   script:
#     - make check-types

pages:
  stage: pages
  image: python:3.8-slim
  allow_failure: false
  script:
    - make run-tests
    - make docs
    - mv doc/tests/ public/
    - pipenv run coverage-run
    - mv coverage public/
    - mv flake-report public/
  artifacts:
    paths:
      - public
