#https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html?highlight=multi_line_output#custom-configuration
[tool.black]
line-length = 80
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
)/
'''
[tool.isort]
profile = "black" 
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap=0
use_parentheses = true
line_length = 88
float_to_top = true
