name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: make set-up
    - name: Generate docs 1
      run:  ls 
    - name: Generate docs 2
      run:  pipenv run coverage-run 
    - name: Generate docs 3
      run:  pipenv run coverage-report
    - name: Generate docs 4
      run:  pipenv run build-coverage-report 
    - name: Generate docs 5
      run:  pipenv run build-linter-report
    - name: Generate docs 6
      run: pipenv run build-docs
    - name: Move coverage
      run:  mv htmlcov public/
    - name: Move flake8
      run:  mv flake-report public/
      
