name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Run tests
      run: cd ../../ && make run-tests
      
    - name: Generate docs
      run:  cd ../../ && make docs && mv coverage docs/ && mv flake-report docs/
      
