name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # run-tests:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Configure
  #     run: make set-up

  #   - name: Run tests
  #     run: make run-tests

  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: make set-up
    - name: Generate docs 1
      run:  pipenv run build-coverage-report 
    - name: Generate docs 2
      run:  pipenv run build-linter-report
    - name: Generate docs 3
      run: pipenv run build-docs
    - name: Move coverage
      run:  mv coverage public/
    - name: Move flake8
      run:  mv flake-report public/
      
