name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  configre:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: make set-up
      
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: make run-tests

  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Generate docs
      run:  make docs && mv coverage docs/ && mv flake-report docs/
      
